# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build
language: node_js
node_js:
  - "9"

sudo: required

services:
  - docker

cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get update && sudo apt-get install curl

install:
  - yarn

before_script:
  - yarn run stylelint
  - yarn run lint
  - yarn run unit

script:
  - yarn run build
  - docker build -t eritikass/ci-test .

after_script:
  - docker ps
  - docker run -d --name ci-test -p "8081:80" eritikass/ci-test
  - docker ps
  - curl "http://localhost:8081/index.html"
